services:
  
  redis:
    image: docker.io/bitnami/redis:7.4
    container_name: redis
    restart: on-failure
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=testpass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - zeroshare
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  db:
    image: postgres
    restart: always
    container_name: db
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: zeroshare
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - zeroshare

  backend:
    image: ghcr.io/jobinlawrance/zeroshare-backend:latest
    container_name: backend
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      nebula-lighthouse:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - APP_ENV=production
    volumes:
      - ./bin:/app/bin
      - ./certs:/app/certs
    networks:
      - zeroshare

  nebula-lighthouse:
    image: debian:bullseye-slim
    container_name: nebula-lighthouse
    healthcheck:
      test: ["CMD", "test", "-f", "./shared-bin/nebula-cert"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./certs:/certs
      - ./config:/config
      - ./bin:/shared-bin
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "-c", "apt-get update && apt-get install -y iputils-ping && /scripts/start-lighthouse.sh"]
    ports:
      - "4242:4242/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true  # Be cautious with this in production
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always
    networks:
      - zeroshare

  uptrace:
    image: 'uptrace/uptrace:1.7.6'
    container_name: uptrace
    restart: on-failure
    volumes:
      - ./otel/uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - '14317:14317'
      - '14318:14318'
    environment:
      - UPTRACE_SELF_TOKEN
      - UPTRACE_ZEROSHARE_TOKEN
      - UPTRACE_PASSWORD
    env_file:
      - .env
    networks:
      - zeroshare  
    depends_on:
      - clickhouse
      - db

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
    environment:
      - UPTRACE_SELF_TOKEN
      - UPTRACE_ZEROSHARE_TOKEN
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - zeroshare
    depends_on:
      - uptrace

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./otel/clickhouse-init:/docker-entrypoint-initdb.d
      - chdata:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 10s
    networks:
      - zeroshare

volumes:
  redis_data:
    driver: local
  pgdata:
    driver: local
  chdata:
    driver: local

networks:
  zeroshare:
    driver: bridge