name: Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags that match the pattern vX.X.X

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: CGO_ENABLED=0 go build -o main .

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-architecture image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jobinlawrance/zeroshare-backend:${{ env.VERSION }}
            ghcr.io/jobinlawrance/zeroshare-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output version
        run: echo "Built and pushed version ${{ env.VERSION }}"